config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users
  # , controllers: {
  #   registrations: 'users/registrations'
  # }

  resources :invits, only: [:index, :show] do
    member do
      get :envoyer 
      get :relancer 
      get :valider 
      get :rejeter 
      get :confirmer 
      get :archiver
      post :validation
    end
    collection do
      post :action
    end
  end

  resources :formations
  resources :intervenants do
    member do
      get :invitations
    end
  end
  resources :users
  resources :fermetures
  resources :etudiants
  resources :documents
  resources :unites

  resources :cours do
    collection do
      get :planning, to: 'cours#index_slide'
      post :action
      post :action_do
    end
  end
    
  resources :salles do
    collection do
      get :occupation
      get :libres
    end
  end

  resources :dossiers do
    member do
      get :deposer
      get :envoyer
      get :valider
      get :rejeter
      get :relancer
      get :archiver
    end
  end

  resources :import_logs do
    member do
      get :download_imported_file
    end
  end

  resources :envoi_logs do
    member do
      get :activer
      get :tester
      get :suspendre
    end
  end

  resources :mail_logs, only: %i[ index show ]

  namespace :tools do
    get :index

    get :import
    get :import_intervenants
    get :import_utilisateurs
    get :import_etudiants
    get :export
    get :export_intervenants
    get :export_utilisateurs
    get :export_etudiants
    get :export_formations
    get :export_vacations

    get :swap_intervenant
    get :etats_services
    get :audits
    get :taux_occupation_jours
    get :taux_occupation_salles
    get :nouvelle_saison
    get :notifier_intervenants
    get :creation_cours
    get :audit_cours
    get :liste_surveillants_examens
    get :rechercher
    get :rappel_des_cours
    get :acces_intervenants

    post :import_do
    post :creation_cours_do
    post :import_intervenants_do
    post :import_utilisateurs_do
    post :import_etudiants_do
    post :export_do
    post :export_intervenants_do
    post :export_utilisateurs_do
    post :export_etudiants_do
    post :export_formations_do
    post :export_vacations_do
    post :swap_intervenant_do
    post :taux_occupation_jours_do
    post :taux_occupation_salles_do
    post :nouvelle_saison_create
    post :notifier_intervenants_do
    post :rappel_des_cours_do
    post :acces_intervenants_do
  end

  get 'guide/index'
  
  # namespace :api, defaults: {format: 'json'} do 
  #   namespace :v1 do 
  #       resources :cours
  #   end 

  #   namespace :v2 do 
  #       resources :cours do
  #         collection do
  #           get :in_progress
  #         end
  #       end
  #       resources :etudiants
  #   end 
  
  #   namespace :v3 do 
  #     resources :cours do
  #       collection do
  #         get :in_progress
  #       end
  #     end
  #   end 

  #   namespace :v4 do 
  #     resources :cours
  #   end 

  # end 

  resources :alerts
  resources :ouvertures
  resources :agents

  root 'cours#index'

end

app/models/salle.rb
# encoding: utf-8

class Salle < ApplicationRecord
	include Discard::Model

	audited
	
	has_many :cours

	default_scope { kept }	
	default_scope { order(:bloc, :nom) } 

	validates :nom, :places, presence: true
	validates :nom, uniqueness: true
	

	def self.salles_de_cours
		Salle.where("LENGTH(nom) = 2").where.not(nom: %w{A8 A20 D7 D8 D9})
	end

	def self.salles_de_cours_du_samedi
		self.salles_de_cours.where("nom like 'D%'")
	end

	def nom_places
		self.places.blank? ? self.nom : "#{self.nom} (#{self.places}P)" 
	end

	def self.nb_heures_journée
		return 6
	end

	def self.nb_heures_soirée
		return 3
	end

	def self.blocs
		self.all.pluck(:bloc).uniq.sort
	end

end

app/controllers/salles_controller.rb
# ENCODING: UTF-8

class SallesController < ApplicationController
  before_action :set_salle, only: [:show, :edit, :update, :destroy]
  before_action :is_user_authorized, except: %i[ libres ]

  # GET /salles
  # GET /salles.json
  def index
    @salles = Salle.order(:nom)

    unless params[:salle_id].blank?
      @salles = @salles.where(id:params[:salle_id])
    end
  end

  def occupation
    params[:vue] ||= 'jour'
    
    @salles = Salle.all

    unless session[:start_date].blank?
      params[:start_date] ||= session[:start_date]
    else
      params[:start_date] ||= Date.today
    end

    unless params[:bloc].blank?
      @salles = @salles.where(bloc: params[:bloc])
    end

    unless params[:salle_id].blank?
      @salles = @salles.where(id: params[:salle_id])
    end

    unless params[:start_date].blank?
      @date = params[:start_date].to_date
    else
      @date = Date.today
    end

    if params[:vue] == 'jour'
      @cours = Cour.where("DATE(cours.debut) =  ?", @date)
                   .where(etat: Cour.etats.values_at(:confirmé, :réalisé))
    else  
      @date_fin = @date + 10.day
      @cours_semaine = Cour.where("cours.debut BETWEEN DATE(?) AND DATE(?)", @date, @date_fin + 1.day)
                           .where(etat: Cour.etats.values_at(:confirmé, :réalisé))
                           .order(:debut) 
    end  

    if user_signed_in?
      #
      # Calcul du taux d'occupation
      #

      # salles concernées
      @salles_dispo = Salle.salles_de_cours.count
      @salles_dispo_samedi = Salle.salles_de_cours_du_samedi.count

      # cumul les heures de cours du jour et du soir
      @nombre_heures_cours = [Cour.cumul_heures(@date).first, 
                              Cour.cumul_heures(@date).last]

      # amplitude 
      @nb_heures_journée = Salle.nb_heures_journée
      @nb_heures_soirée = Salle.nb_heures_soirée

      # nombre d'heures salles
      @heures_dispo_salles = [@salles_dispo * @nb_heures_journée, 
                              @salles_dispo_samedi * @nb_heures_soirée] 

      # taux d'occupation
      unless @heures_dispo_salles.first.zero?
        taux_occupation_matin = @nombre_heures_cours.first * 100 / @heures_dispo_salles.first
      else
        taux_occupation_matin = 0
      end 
      
      unless @heures_dispo_salles.last.zero?
        taux_occupation_soir  = @nombre_heures_cours.last * 100 / @heures_dispo_salles.last
      else  
        taux_occupation_soir  = 0
      end

      @taux_occupation = [taux_occupation_matin, taux_occupation_soir]
    end

    @etendue_horaire = Cour.etendue_horaire

    session[:start_date] = params[:start_date]
  end

  # GET /salles/1
  # GET /salles/1.json
  def show
    @audits = Audited::Audit
                  .where(auditable_type: 'Cour')
                  .where("audited_changes like '%salle_id%'")
                  .order('id DESC')
                  .limit(10000)

  end

  # GET /salles/new
  def new
    @salle = Salle.new
  end

  # GET /salles/1/edit
  def edit

  end

  # POST /salles
  # POST /salles.json
  def create
    @salle = Salle.new(salle_params)

    respond_to do |format|
      if @salle.save
        format.html { redirect_to @salle, notice: 'Salle ajoutée.' }
        format.json { render :show, status: :created, location: @salle }
      else
        format.html { render :new }
        format.json { render json: @salle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salles/1
  # PATCH/PUT /salles/1.json
  def update
    respond_to do |format|
      if @salle.update(salle_params)
        format.html { redirect_to @salle, notice: 'Salle modifiée.' }
        format.json { render :show, status: :ok, location: @salle }
      else
        format.html { render :edit }
        format.json { render json: @salle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salles/1
  # DELETE /salles/1.json
  def destroy
    @salle.destroy
    respond_to do |format|
      format.html { redirect_to salles_path, notice: 'Salle supprimé.' }
      format.json { head :no_content }
    end
  end

  # Afficher les salles disponibles en JSON
  def libres
    salles_dispos_ids = []
    cours = nil

    if !(params[:id].blank?)
      cours = Cour.find(params[:id])
    elsif !(params[:date].blank? || params[:duree].blank? || params[:formation_id].blank? || params[:intervenant_id].blank?)
      cours = Cour.new(debut: DateTime.parse(params[:date]), 
                        duree: params[:duree], 
                        formation_id: params[:formation_id], 
                        intervenant_id: params[:intervenant_id],
                        salle_id: Salle.first.id)
    end

    if cours
      # Test chaque salle pour voir les disponibilités (cours.valid? == true)
      Salle.all.each do |s|
        cours.salle = s 
        if cours.valid?
          salles_dispos_ids << s.id
        end 
      end
    end

    #logger.debug salles_dispos_ids

    respond_to do |format|
      format.json do
        render json: Salle.where(id: salles_dispos_ids).to_json
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salle
      @salle = Salle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salle_params
      params.require(:salle).permit(:nom, :places, :bloc)
    end

    def is_user_authorized
      authorize Salle
    end
end

app/helpers/salles_helper.rb
module SallesHelper
end

app/views/salles/_form.html.erb
<%= bootstrap_form_for(@salle) do |f| %>
  <% if @salle.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  
      <h3><%= t('activerecord.errors.template.header',
                  model: Salle.model_name.human, count: @salle.errors.count) %></h3>
      <ul>
      <% @salle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-3">

      <%= f.text_field :nom %>
      <%= f.text_field :bloc %>
      <%= f.number_field :places, label:"Nombre de places" %><i><small>Entrez 0 pour autoriser les doublons</small></i>
      <br><br>
      <%= f.submit class: "btn btn-primary", 'data-turbo': false %>
    </div>
  </div>  
<% end %>

app/views/salles/_occupation_jour.html.erb
<div class="table-responsive">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th>Salle</th>
        <th>Places</th>
        <th>Formations</th> 
        <th>Cours</th>
        <% @etendue_horaire.each_with_index do |heure, index| %>
          <th class="<%= 'alert alert-warning' if ((@date == Date.today) && (heure == time_in_paris.hour)) %>"><%= heure %>h</th>
          <% if [4,9].include?(index) %><th></th><th></th><% end %>
        <% end %>
      </tr>
    </thead>

    <tfoot>
      <tr><th colspan=22></th></tr>
    </tfoot>

    <tbody>
      <% bloc = 'A' %>
      <% @salles.each do | salle | %>
        <% cours = @cours.where(salle_id: salle.id) %>
        <% cours_count = cours.length %>

        <% if params[:bloc].blank? && salle.bloc != bloc %>
          <% bloc = salle.bloc %>
          <thead>
            <tr>
              <th colspan=4></th>
              <% @etendue_horaire.each_with_index do |heure, index| %>
                <th class="<%= 'alert alert-warning' if ((@date == Date.today) && (heure == time_in_paris.hour)) %>"><%= heure %>h</th>
                <% if [4,9].include?(index) %><th></th><th></th><% end %>
              <% end %>
            </tr>
          </thead>
        <% end %>

        <tr class="shadow-sm">
          <td><b><%= salle.nom[0..7] %></b></td>
          <td class="text-right"><%= salle.places %></td>
          <td>
            <% cours.pluck(:formation_id).uniq.each do |id| %> 
                <% formation = Formation.unscoped.find(id) %> 
                <span style="background-color:<%= formation.color %>;padding-left: 7px;"></span> 
                <span style="padding-left:5px;"></span> 
                <%= formation.nom_abrg_nbr_etudiants %> 
                <span style="padding-right:10px;"></span> 
            <% end %> 
          </td>
          <td class="text-right">
            <%= link_to_unless cours_count.zero?, cours_count, 
                              cours_path(ids:cours.pluck(:id), view:'list', from:'occupation') %>
          </td>

          <% if @date %>
            <% range = [] %>
            <% cours.each {|cours| range += cours.range } %>
            <% map = @etendue_horaire.map {|i| range.include?(i) ? 'red' : 'lightgreen' } %>
            
            <% map.each_with_index do |color, index| %>
              <td class="<%= 'text-center alert alert-warning' if ((@date == Date.today) && ((index + 8) == time_in_paris.hour)) %>">
                <% if color == 'lightgreen' %>
                  <%= link_to new_cour_path(debut: @date, heure: (index + 8), salle_id: salle.id, from: 'occupation') do %>
                    <span style="background-color:<%= color %>;padding-left: 15px;"></span>
                  <% end %>
                <% else %>
                  <% debut_cours = DateTime.parse("#{@date} #{index + 8}:00") %>
                  <% nom_formation = Formation.select(:nom).joins(:cours).where('cours.debut <= ?', debut_cours).where('cours.fin >= ?', debut_cours).where('cours.salle_id': salle.id).limit(1).pluck(:nom) %>
                  <%= link_to '#', title: nom_formation do %>
                    <span style="background-color: <%= color %>;padding-left: 15px;"></span> 
                  <% end %>
                <% end %>
              </td>
              <% if [4,9].include?(index) %><th></th><th></th><% end %>
            <% end %>
          <% else %>
            <td colspan="18"></td>
          <% end %>
          <td><b><%= salle.nom[0..2] %></b></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if false %>
    <div class="row">
      <div class="col-sm-6">
        <h5>
          Heures de cours planifiées jour: <%= @nombre_heures_cours.first %>h <br>
          Heures de salles disponibles jour: <%= @heures_dispo_salles.first %>h
           (<%= @salles_dispo %> salles * <%= @nb_heures_journée %>h)<br>
        </h5>
      </div>
      <div class="col-sm-6">
        <h4>
          Taux d'occupation jour: <%= @taux_occupation.first.to_i %>%
        </h4>
      </div>
    </h4>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <h5>
          Heures de cours planifiées soir: <%= @nombre_heures_cours.last %>h <br>
          Heures de salles disponibles soir: <%= @heures_dispo_salles.last %>h
           (<%= @salles_dispo %> salles * <%= @nb_heures_soirée %>h)<br>
        </h5>
      </div>
      <div class="col-sm-6">
        <h4>
          Taux d'occupation soir: <%= @taux_occupation.try(:last).try(:to_i) %>%
        </h4>
      </div>
    </h4>
  </div>
<% end %>
<br>

app/views/salles/_occupation_week.html.erb
<div class="table-responsive">
  <table class="table table-hover table-striped table-sm">
    <thead>
      <tr>
        <th>Salle</th>
        <th>Places</th>
        <th>Cours</th>
        <% (@date..@date_fin).each do |d| %>
          <th>
            <%= l(d, format: :day).humanize %>
            <%= d.day %>
           </th>
        <% end %> 
      </tr>
    </thead>

    <tfoot>
      <tr>
        <th colspan=21></th>
      </tr>
    </tfoot>

    <tbody>
      <% bloc = 'A' %>
      <% @salles.each do | salle | %>
        <% @cours = @cours_semaine.where(salle_id: salle.id) %>

        <% if salle.bloc != bloc %>
          <% bloc = salle.bloc %>
          <thead>
            <tr>
              <th></th><th></th><th></th>
              <% (@date..@date_fin).each do |d| %>
                <th>
                  <%= l(d, format: :day).humanize %>
                  <%= d.day %>
                </th>
              <% end %> 
            </tr>
          </thead>
        <% end %>

        <tr>
          <td><b><%= salle.nom %></b></td>
          <td class="text-center"><%= salle.places %></td>
          <td class="text-center">
            <%= link_to_if user_signed_in?, @cours.count, cours_path(ids: @cours.pluck(:id), view: 'list', from: 'occupation') %>
          </td>
          <% (@date..@date_fin).each do | d | %>
            <td>
              <% cours = @cours.where("DATE(cours.debut) = ?", d) %>
            
              <% color = cours.where("debut < ?", Time.parse(d.to_s + " 13:00")).any? ? 'red' : 'lightgreen' %>
              <span style="background-color:<%= color %>;padding-left: 15px;"></span>

              <% color = cours.where("debut >= ? AND debut <= ?", Time.parse(d.to_s + " 13:00"), Time.parse(d.to_s + " 18:00")).any? ? 'red' : 'lightgreen' %>
              <span style="background-color:<%= color %>;padding-left: 15px;"></span>

              <% color = cours.where("debut >= ?", Time.parse(d.to_s + " 18:00")).any? ? 'red' : 'lightgreen' %>
              <span style="background-color:<%= color %>;padding-left: 15px;"></span>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/salles/_salle.html.erb
<tr>
    <td><%= link_to salle.nom, salle %></td>
    <td><%= salle.places %></td>
    <td><%= salle.bloc %></td>
    <td class="text-center">
        <% unless Cour.where(salle_id: salle).any? %>
            <%= link_to(salle, method: :delete, data: {confirm: 'Confirmez-vous ?'}, class: "btn btn-default") do %>
                <%= fa_icon 'trash' %>
            <% end %>
        <% end %>
    </td>
</tr>

app/views/salles/edit.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
	<%= link_to salles_path, class: 'btn text-primary float-end' do %>
		<%= fa_icon 'list-alt' %> Retour
	<% end %>

	<%= link_to @salle, class: 'btn text-primary float-end' do %>
	   	<%= fa_icon 'eye', text: 'Voir' %>
	<% end %>

	<h3><%= fa_icon 'chalkboard' %> Modification d'une salle</h3>
</div>

<%= render 'form' %>

app/views/salles/index.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <%= link_to new_salle_path, class: 'btn text-primary float-end' do %>
    <%= fa_icon 'plus-circle' %> Ajouter
  <% end %>
  <h3><%= fa_icon 'chalkboard' %> Liste des salles</h3>
</div>

<div class='container-fluid'>
    <%= form_tag request.path, method: :get do %>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-2">
            <%= label_tag "Salle" %>    
              <%= select_tag :salle_id, 
                      options_from_collection_for_select(Salle.order(:nom), :id, :nom, params[:salle_id]), 
                        include_blank:true, onchange:'this.form.submit()', class:"form-control" %>
          </div>
        </div>
      </div>  
    <% end %>
</div>

<div class="table-responsive">
  <table class="table table-hover table-striped table-sm">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Nbr places</th>
        <th>Bloc</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tfoot>
      <tr>
        <th /><th /><th /><th />
      </tr>
    </tfoot>

    <tbody>
        <%= render @salles %>
    </tbody>
  </table>
</div>
<br>

app/views/salles/new.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
	<%= link_to salles_path, class: 'btn text-primary float-end' do %>
		<%= fa_icon 'list-alt' %> Retour
	<% end %>
	<h3><%= fa_icon 'chalkboard' %> Ajouter une salle</h3>
</div>

<%= render 'form' %>

app/views/salles/occupation.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h3><%= fa_icon 'chalkboard' %> Occupation des salles</h3>
</div>

<div class="container-fluid p-3 shadow-sm">

  <%= form_tag request.path, method: :get do %>
    <div class="row">

      <div class="col-sm-3">
        <%= label_tag "Date" %>    
        <%= text_field_tag :start_date, params[:start_date], type:'date', onchange:'this.form.submit()', class:"form-control form-control-sm" %>
      </div>

      <div class="col-sm-2">
        <%= label_tag "Batiment" %>
        <%= select_tag :bloc, 
                    options_for_select(Salle.blocs, params[:bloc]), 
                    include_blank:true, onchange:'this.form.submit()', class:"form-control form-control-sm" %>
      </div>

      <div class="col-sm-2">
        <%= label_tag "Salle" %>
        <%= select_tag :salle_id, 
                    options_from_collection_for_select((params[:bloc].blank? ? Salle.all : Salle.where(bloc: params[:bloc])), :id, :nom, params[:salle_id]), 
                    include_blank:true, onchange:'this.form.submit()', class:"form-control form-control-sm" %>
      </div>

      <div class="col-sm-3">
        <%= label_tag "Vue" %>
        <br> 
        <%= radio_button_tag :vue, "jour", (params[:vue]=='jour'), onchange:'this.form.submit()' %>
        Journée 
        <%= radio_button_tag :vue, "week", (params[:vue]=='week'), onchange:'this.form.submit()' %>
        Semaine
      </div>

    </div>
  <% end %>
</div>
<br>

<%= render partial: "occupation_#{ params[:vue] }" %>

app/views/salles/show.html.erb
<div class="pb-2 mt-4 mb-2 border-top">
  <div class="btn-group float-end">
    <% if policy(@salle).edit? %>
      <%= link_to edit_salle_path(@salle), class: 'btn btn-sm btn-outline-primary' do %>
        <%= fa_icon 'edit' %> Modifier
      <% end %>
    <% end %>

    <a href="#audit" data-bs-toggle="collapse" class='btn btn-sm btn-outline-primary'>
      <%= fa_icon 'search' %> Audit
    </a>

    <%= link_to salles_path, class: 'btn btn-sm btn-outline-primary' do %>
      <%= fa_icon 'list' %> Retour
    <% end %>
  </div>

  <h2>
    Salle <%= @salle.nom %>
  </h2>
</div>


<p>
  <strong>Nom:</strong>
  <%= @salle.nom %>
</p>

<p>
  <strong>Bloc:</strong>
  <%= @salle.bloc %>
</p>

<p>
  <strong>Places:</strong>
  <%= @salle.places %>
</p>

<hr>
<br>

<div id="audit" class="collapse">
  <h4>Audit des modifications</h4>
  <table class="table table-bordered table-hover table-sm">
    <thead>
      <th>Date</th>
      <th>Utilisateur</th>            
      <th>Type</th>
      <th>Record_id</th>
      <th>Action</th>
      <th>Modifications</th>
    </thead>
    <tbody>
      <%= render partial: 'tools/audit', collection: @salle.audits.includes(:user).reverse %>
    </tbody>
  </table>

  <h4>
    Audit des attributions
  </h4>

  <table class="table table-bordered table-striped table-hover table-sm">
    <thead>
      <th>Date</th>
      <th>Qui</th>
      <th>Cours</th>
      <th>Formation</th>
      <th>Date du cours</th>
      <th>Action Salle</th>
    </thead>
    <% @audits.includes(:user).each do |audit| %>
        <% if extract_salle_id(audit) == @salle.id %>
            <% if cour = Cour.where(id: audit.auditable_id).first %>
              <tr>
                <td><%= l(audit.created_at, format: :perso) %></td>
                <td><%= audit.try(:user).try(:email) %></td>
                <td><%= link_to audit.auditable_id, cour_path(cour) %></td>
                <td><%= cour.try(:formation).try(:nom) %></td>
                <td><%= l(cour.debut, format: :perso) %></td>
                <td><%= convertir_id_salles(audit) %></td>
              </tr>
            <% end %>  
        <% end %>
      <% end %>  
  </table>
</div>